#!/usr/bin/env python3
from __future__ import annotations

import argparse
import math
import re
from pathlib import Path


DEFAULT_SHARED_SUPPORT = Path("/Library/Input Methods/Squirrel.app/Contents/SharedSupport")
DEFAULT_OPENXIAMI_SOURCES = (
    Path("rime/openxiami_TCJP.dict.yaml"),
    Path("rime/openxiami_TradExt.dict.yaml"),
)
CJK_SINGLE = re.compile(r"^[\u3400-\u9fff]$")
PINYIN_CODE = re.compile(r"^[a-z]+$")


def iter_rime_data(path: Path):
    in_data = False
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        if raw == "...":
            in_data = True
            continue
        if not in_data or not raw or raw.startswith("#") or "\t" not in raw:
            continue
        yield raw.split("\t")


def load_liur_chars(paths: list[Path]) -> set[str]:
    chars: set[str] = set()
    for path in paths:
        for parts in iter_rime_data(path):
            if len(parts) < 2:
                continue
            text, code = parts[0].strip(), parts[1].strip()
            if not CJK_SINGLE.match(text):
                continue
            if any("\u3040" <= ch <= "\u30ff" for ch in text):
                continue
            if "," in code or "." in code:
                continue
            chars.add(text)
    return chars


def load_single_char_freq(path: Path) -> dict[str, int]:
    freqs: dict[str, int] = {}
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        if not raw or raw.startswith("#") or "\t" not in raw:
            continue
        parts = raw.split("\t")
        if len(parts) < 2:
            continue
        text, value = parts[0].strip(), parts[1].strip()
        if CJK_SINGLE.match(text) and value.isdigit():
            freqs[text] = max(freqs.get(text, 0), int(value))
    return freqs


def pinyin_weight(code: str, freq: int) -> int:
    # Keep pinyin single-character entries between same-length liur hits and
    # next-longer liur completions. Example: hu-liur 9800 > hu-pinyin > hua-liur 9700.
    base = 9950 - len(code) * 100
    bonus = min(49, int(math.log10(freq + 1) * 12)) if freq > 0 else 0
    return max(1, base + bonus)


def export_pinyin_liur(luna_pinyin: Path, essay: Path, liur_sources: list[Path], output: Path) -> int:
    liur_chars = load_liur_chars(liur_sources)
    freqs = load_single_char_freq(essay)
    seen: set[tuple[str, str]] = set()
    rows: list[tuple[str, str, int, int]] = []

    for parts in iter_rime_data(luna_pinyin):
        if len(parts) < 2:
            continue
        text, code = parts[0].strip(), parts[1].strip()
        if not CJK_SINGLE.match(text):
            continue
        if text not in liur_chars or not PINYIN_CODE.match(code):
            continue
        key = (text, code)
        if key in seen:
            continue
        seen.add(key)
        freq = freqs.get(text, 0)
        rows.append((text, code, pinyin_weight(code, freq), freq))

    rows.sort(key=lambda row: (row[1], -row[2], -row[3], row[0]))

    lines = [
        "# Rime dictionary",
        "# encoding: utf-8",
        "# Generated by tools/export_pinyin_liur.py.",
        "# Single-character pinyin entries limited to characters present in openxiami tables.",
        "",
        "---",
        "name: xiapin_pinyin_liur",
        'version: "0.1.0"',
        "sort: by_weight",
        "...",
    ]
    lines.extend(f"{text}\t{code}\t{weight}" for text, code, weight, _freq in rows)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate xiapin pinyin/openxiami intersection dictionary.")
    parser.add_argument("--luna-pinyin", type=Path, default=DEFAULT_SHARED_SUPPORT / "luna_pinyin.dict.yaml")
    parser.add_argument("--essay", type=Path, default=DEFAULT_SHARED_SUPPORT / "essay.txt")
    parser.add_argument("--liur", type=Path, action="append", default=None)
    parser.add_argument("--output", type=Path, default=Path("rime/xiapin_pinyin_liur.dict.yaml"))
    args = parser.parse_args()

    liur_sources = args.liur if args.liur is not None else list(DEFAULT_OPENXIAMI_SOURCES)
    count = export_pinyin_liur(args.luna_pinyin, args.essay, liur_sources, args.output)
    print(f"generated {count} entries: {args.output}")


if __name__ == "__main__":
    main()
